<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Controls\NotificationControl.Designer.cs">
      <DependentUpon>NotificationControl.cs</DependentUpon>
    </Compile>
    <Compile Update="Controls\ModernDataGridView.Designer.cs">
      <DependentUpon>ModernDataGridView.cs</DependentUpon>
    </Compile>
    <Compile Update="Controls\ReusableDataGrid.Designer.cs">
      <DependentUpon>ReusableDataGrid.cs</DependentUpon>
    </Compile>
    <Compile Update="Controls\ProductsControl.Designer.cs">
      <DependentUpon>ProductsControl.cs</DependentUpon>
    </Compile>
    <Compile Update="Controls\ModernTitleBar.Designer.cs">
      <DependentUpon>ModernTitleBar.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\ProductDialog.Designer.cs">
      <DependentUpon>ProductDialog.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\ProductSettingsDialog.Designer.cs">
      <DependentUpon>ProductSettingsDialog.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\ProductUnitDialog.Designer.cs">
      <DependentUpon>ProductUnitDialog.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\ProductUnitsDialog.Designer.cs">
      <DependentUpon>ProductUnitsDialog.cs</DependentUpon>
    </Compile>
    <Compile Update="Forms\UnitDialog.Designer.cs">
      <DependentUpon>UnitDialog.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Syncfusion.Core.WinForms" Version="32.1.22" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="32.1.22" />
    <PackageReference Include="Syncfusion.Tools.Windows" Version="32.1.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RMS_Business\RMS_Business.csproj" />
    <ProjectReference Include="..\RMS_DataAccess\RMS_DataAccess.csproj" />
  </ItemGroup>

</Project>